// Small offline dictionary for the highest-traffic UI strings so the toggle
// feels instant. Everything else is translated on demand via /api/translate.
export const DICT: Record<string, string> = {
  "เข้าสู่ระบบ": "Sign in",
  "สมัครสมาชิก": "Sign up",
  "เข้าสู่ระบบ / สมัครสมาชิก": "Sign in / Sign up",
  "บัญชีของฉัน": "My account",
  "ค้นหาสินค้า...": "Search products...",
  "ค้นหาสินค้า, ยี่ห้อ, หรือปัญหาผิวที่กังวล...": "Search products, brands or skin concerns...",
  "สินค้าทั้งหมด": "All products",
  "แบรนด์ทั้งหมด": "All brands",
  "โปรโมชั่น": "Promotions",
  "ตัวกรอง": "Filters",
  "หมวดหมู่": "Category",
  "แบรนด์": "Brand",
  "ทั้งหมด": "All",
  "เรียงตาม": "Sort by",
  "แนะนำ": "Recommended",
  "ขายดีที่สุด": "Best selling",
  "เพิ่มลงตะกร้า": "Add to cart",
  "เริ่มช้อปเลย": "Start shopping",
  "ตะกร้าสินค้า": "Shopping cart",
  "ตะกร้าของคุณว่างเปล่า": "Your cart is empty",
  "สรุปคำสั่งซื้อ": "Order summary",
  "ยอดรวมสินค้า": "Subtotal",
  "ค่าจัดส่ง": "Shipping",
  "ยอดรวมทั้งหมด": "Total",
  "ฟรี": "Free",
  "ดำเนินการชำระเงิน": "Proceed to checkout",
  "คูปองส่วนลด": "Coupons",
  "คะแนนที่จะได้รับ": "Points you'll earn",
  "คะแนน": "points",
  "กำลังโหลด...": "Loading...",
  "ดูทั้งหมด": "View all",
  "ยกเลิก": "Cancel",
  "ย้อนกลับ": "Back",
  "กำลังคิด...": "Thinking...",
  "พิมพ์คำถามของคุณ...": "Type your question...",
  "คุยกับน้อง Smoothie": "Chat with Smoothie",
};
