// AI features are intentionally local-development only. Production builds
// generated by Git/Vercel compile this flag to false and never expose the UI.
export const LOCAL_AI_ENABLED = process.env.NODE_ENV === "development";
