import { adminGraphql } from "@/lib/shopify-admin";

// Discount codes, priced by the shop that issued them.
//
// The codes themselves live in Shopify — created in Admin, in campaigns, or
// by our own reward flows — and so does the arithmetic. A draft order is the
// honest way to ask "what would this code take off this cart?": Shopify runs
// the same rules it would run at checkout (minimum spend, which products or
// collections qualify, per-customer limits, expiry) and answers with money.
// We never re-implement those rules here, because a second implementation is
// a second set of answers, and the customer would eventually be shown one
// while being charged the other.

export type DiscountQuote =
  | { ok: true; code: string; title: string; discount: number }
  | { ok: false; reason: string };

type CodeDiscountNode = {
  codeDiscount: {
    __typename: string;
    title?: string;
    status?: string;
    summary?: string;
    endsAt?: string | null;
    codes?: { nodes: { code: string }[] };
  };
};

/**
 * The codes the shop has chosen to advertise on the website.
 *
 * Most active codes in a store are not for showing anyone: single-use
 * free-shipping codes generated by apps, subscription codes, and the reward
 * codes we mint per customer — listing those would hand every visitor someone
 * else's discount. So the shop opts a code in by naming it, in Shopify Admin,
 * with a "WEB:" prefix. Nothing else is ever listed.
 */
export async function listWebDiscountCodes(): Promise<{ code: string; title: string; summary: string }[]> {
  const data = await adminGraphql<{ codeDiscountNodes: { nodes: CodeDiscountNode[] } }>(
    `query WebDiscounts {
      codeDiscountNodes(first: 100, query: "status:active") {
        nodes {
          codeDiscount {
            __typename
            ... on DiscountCodeBasic { title status summary endsAt codes(first: 1) { nodes { code } } }
            ... on DiscountCodeBxgy { title status summary endsAt codes(first: 1) { nodes { code } } }
            ... on DiscountCodeFreeShipping { title status summary endsAt codes(first: 1) { nodes { code } } }
          }
        }
      }
    }`
  );

  return data.codeDiscountNodes.nodes
    .map((n) => n.codeDiscount)
    .filter((d) => /^web:/i.test(d.title ?? ""))
    .map((d) => ({
      code: d.codes?.nodes[0]?.code ?? "",
      title: (d.title ?? "").replace(/^web:\s*/i, ""),
      summary: d.summary ?? "",
    }))
    .filter((d) => d.code);
}

/** Whether a code exists at all, and whether it is live — for a useful error. */
async function lookupCode(code: string): Promise<{ title: string; status: string } | null> {
  const data = await adminGraphql<{ codeDiscountNodeByCode: CodeDiscountNode | null }>(
    `query FindCode($code: String!) {
      codeDiscountNodeByCode(code: $code) {
        codeDiscount {
          __typename
          ... on DiscountCodeBasic { title status }
          ... on DiscountCodeBxgy { title status }
          ... on DiscountCodeFreeShipping { title status }
        }
      }
    }`,
    { code }
  );
  const d = data.codeDiscountNodeByCode?.codeDiscount;
  return d ? { title: d.title ?? code, status: d.status ?? "ACTIVE" } : null;
}

/**
 * What this code takes off this cart, according to Shopify.
 *
 * The draft order is a question, not an order: it is created, read, and
 * deleted, it charges nobody and it does not consume a code's usage limit.
 * Shopify answers an unknown or unusable code the same quiet way — it simply
 * applies nothing and hands back an empty discountCodes — so the code is
 * looked up separately to tell the customer which of the two happened.
 */
export async function quoteDiscountCode(opts: {
  code: string;
  lines: { variantId: string; quantity: number }[];
}): Promise<DiscountQuote> {
  const code = opts.code.trim();
  if (!code) return { ok: false, reason: "กรุณากรอกโค้ดส่วนลด" };
  if (!opts.lines.length) return { ok: false, reason: "ตะกร้ายังไม่มีสินค้า" };

  const found = await lookupCode(code);
  if (!found) return { ok: false, reason: "ไม่พบโค้ดนี้ในระบบ" };
  if (found.status !== "ACTIVE") {
    return { ok: false, reason: found.status === "EXPIRED" ? "โค้ดนี้หมดอายุแล้ว" : "โค้ดนี้ยังไม่เปิดใช้งาน" };
  }

  const data = await adminGraphql<{
    draftOrderCreate: {
      draftOrder: {
        id: string;
        discountCodes: string[];
        totalDiscountsSet: { shopMoney: { amount: string } };
      } | null;
      userErrors: { message: string }[];
    };
  }>(
    `mutation QuoteDiscount($input: DraftOrderInput!) {
      draftOrderCreate(input: $input) {
        draftOrder {
          id
          discountCodes
          totalDiscountsSet { shopMoney { amount } }
        }
        userErrors { field message }
      }
    }`,
    { input: { lineItems: opts.lines.map((l) => ({ variantId: l.variantId, quantity: l.quantity })), discountCodes: [code] } }
  );

  const draft = data.draftOrderCreate.draftOrder;
  if (!draft) {
    const why = data.draftOrderCreate.userErrors.map((e) => e.message).join(", ");
    console.error("[discounts] draft order quote failed", why);
    return { ok: false, reason: "ตรวจสอบโค้ดไม่สำเร็จ กรุณาลองใหม่อีกครั้ง" };
  }

  // Ask and forget. A draft left behind would sit in the shop's Drafts list
  // looking like an order somebody abandoned.
  void discardDraft(draft.id);

  const discount = Math.round(parseFloat(draft.totalDiscountsSet.shopMoney.amount) || 0);
  if (!draft.discountCodes.length || discount <= 0) {
    return { ok: false, reason: "โค้ดนี้ใช้กับสินค้าในตะกร้าไม่ได้ หรือยอดยังไม่ถึงขั้นต่ำ" };
  }

  return { ok: true, code, title: found.title.replace(/^web:\s*/i, ""), discount };
}

async function discardDraft(id: string) {
  try {
    await adminGraphql(`mutation DiscardDraft($id: ID!) { draftOrderDelete(input: { id: $id }) { deletedId } }`, { id });
  } catch (err) {
    console.error("[discounts] could not delete the quote draft order", err);
  }
}
