import { adminGraphql } from "@/lib/shopify-admin";

const STOREFRONT_DOMAIN = process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN || "";
const STOREFRONT_TOKEN = process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN || "";
const STOREFRONT_VERSION = process.env.NEXT_PUBLIC_SHOPIFY_API_VERSION || "2025-10";

async function storefrontGraphql<T>(query: string, variables?: Record<string, unknown>): Promise<T> {
  const res = await fetch(`https://${STOREFRONT_DOMAIN}/api/${STOREFRONT_VERSION}/graphql.json`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "X-Shopify-Storefront-Access-Token": STOREFRONT_TOKEN },
    body: JSON.stringify({ query, variables }),
    cache: "no-store",
  });
  const json = await res.json();
  if (json.errors?.length) throw new Error(json.errors.map((e: { message: string }) => e.message).join(", "));
  return json.data as T;
}

// Discount codes, priced by the shop that issued them.
//
// The codes themselves live in Shopify — created in Admin, in campaigns, or
// by our own reward flows — and so does the arithmetic. A draft order is the
// honest way to ask "what would this code take off this cart?": Shopify runs
// the same rules it would run at checkout (minimum spend, which products or
// collections qualify, per-customer limits, expiry) and answers with money.
// We never re-implement those rules here, because a second implementation is
// a second set of answers, and the customer would eventually be shown one
// while being charged the other.

export type DiscountQuote =
  | { ok: true; code: string; title: string; discount: number }
  | { ok: false; reason: string };

type CodeDiscountNode = {
  codeDiscount: {
    __typename: string;
    title?: string;
    status?: string;
    summary?: string;
    endsAt?: string | null;
    codes?: { nodes: { code: string }[] };
  };
};

/**
 * The codes the shop has chosen to advertise on the website.
 *
 * Most active codes in a store are not for showing anyone: single-use
 * free-shipping codes generated by apps, subscription codes, and the reward
 * codes we mint per customer — listing those would hand every visitor someone
 * else's discount. So the shop opts a code in by naming it, in Shopify Admin,
 * with a "WEB:" prefix. Nothing else is ever listed.
 */
export async function listWebDiscountCodes(): Promise<{ code: string; title: string; summary: string }[]> {
  const data = await adminGraphql<{ codeDiscountNodes: { nodes: CodeDiscountNode[] } }>(
    `query WebDiscounts {
      codeDiscountNodes(first: 100, query: "status:active") {
        nodes {
          codeDiscount {
            __typename
            ... on DiscountCodeBasic { title status summary endsAt codes(first: 1) { nodes { code } } }
            ... on DiscountCodeBxgy { title status summary endsAt codes(first: 1) { nodes { code } } }
            ... on DiscountCodeFreeShipping { title status summary endsAt codes(first: 1) { nodes { code } } }
          }
        }
      }
    }`
  );

  return data.codeDiscountNodes.nodes
    .map((n) => n.codeDiscount)
    .filter((d) => /^web:/i.test(d.title ?? ""))
    .map((d) => ({
      code: d.codes?.nodes[0]?.code ?? "",
      title: (d.title ?? "").replace(/^web:\s*/i, ""),
      summary: d.summary ?? "",
    }))
    .filter((d) => d.code);
}

/**
 * Whether a code exists at all, and whether it is live — for a useful error.
 *
 * null means Shopify was asked and has no such code. undefined means the
 * question could not be put, which is a different thing entirely: telling
 * someone their real code does not exist because our own lookup was down is
 * worse than saying nothing specific.
 */
async function lookupCode(code: string): Promise<{ title: string; status: string } | null> {
  const data = await adminGraphql<{ codeDiscountNodeByCode: CodeDiscountNode | null }>(
    `query FindCode($code: String!) {
      codeDiscountNodeByCode(code: $code) {
        codeDiscount {
          __typename
          ... on DiscountCodeBasic { title status }
          ... on DiscountCodeBxgy { title status }
          ... on DiscountCodeFreeShipping { title status }
        }
      }
    }`,
    { code }
  );
  const d = data.codeDiscountNodeByCode?.codeDiscount;
  return d ? { title: d.title ?? code, status: d.status ?? "ACTIVE" } : null;
}

/**
 * What this code takes off this cart, according to Shopify.
 *
 * Priced by building a Storefront cart — the same cart object, and the same
 * discount engine, a customer would be using if they checked out on Shopify's
 * own pages. It answers with the allocations it made, so a code's own effect
 * can be told apart from any automatic discount running alongside it, and it
 * costs the shop nothing: the cart is never completed and expires on its own.
 *
 * (A draft order would answer the same question, but only for an app holding
 * write_draft_orders, which this one does not — and asking for a write
 * permission to ask a read-only question is the wrong trade.)
 */
export async function quoteDiscountCode(opts: {
  code: string;
  lines: { variantId: string; quantity: number }[];
}): Promise<DiscountQuote> {
  const code = opts.code.trim();
  if (!code) return { ok: false, reason: "กรุณากรอกโค้ดส่วนลด" };
  if (!opts.lines.length) return { ok: false, reason: "ตะกร้ายังไม่มีสินค้า" };
  if (!STOREFRONT_DOMAIN || !STOREFRONT_TOKEN) {
    console.error("[discounts] storefront credentials missing");
    return { ok: false, reason: "ตรวจสอบโค้ดไม่สำเร็จ กรุณาลองใหม่อีกครั้ง" };
  }

  type Allocation = { __typename: string; code?: string; discountedAmount: { amount: string } };
  const [details, cart] = await Promise.all([
    // Only to say something useful when a code does not work. Best-effort:
    // the answer below does not depend on it.
    lookupCode(code).catch(() => undefined),
    storefrontGraphql<{
      cartCreate: {
        cart: {
          discountCodes: { code: string; applicable: boolean }[];
          discountAllocations: Allocation[];
          lines: { nodes: { discountAllocations: Allocation[] }[] };
        } | null;
        userErrors: { message: string }[];
      };
    }>(
      `mutation QuoteDiscount($input: CartInput!) {
        cartCreate(input: $input) {
          cart {
            discountCodes { code applicable }
            discountAllocations {
              __typename
              discountedAmount { amount }
              ... on CartCodeDiscountAllocation { code }
            }
            lines(first: 100) {
              nodes {
                discountAllocations {
                  __typename
                  discountedAmount { amount }
                  ... on CartCodeDiscountAllocation { code }
                }
              }
            }
          }
          userErrors { field message }
        }
      }`,
      {
        input: {
          lines: opts.lines.map((l) => ({ merchandiseId: l.variantId, quantity: l.quantity })),
          discountCodes: [code],
        },
      }
    ).catch((err) => {
      console.error("[discounts] storefront quote failed", err);
      return null;
    }),
  ]);

  if (!cart?.cartCreate.cart) {
    return { ok: false, reason: "ตรวจสอบโค้ดไม่สำเร็จ กรุณาลองใหม่อีกครั้ง" };
  }
  const priced = cart.cartCreate.cart;

  // Only what this code did. An automatic discount the shop is running is
  // real money off too, but it applies with or without the customer typing
  // anything, and counting it here would credit the coupon with it.
  const mine = (a: Allocation) =>
    a.__typename === "CartCodeDiscountAllocation" && (a.code ?? "").toLowerCase() === code.toLowerCase();
  const discount = Math.round(
    [...priced.discountAllocations, ...priced.lines.nodes.flatMap((l) => l.discountAllocations)]
      .filter(mine)
      .reduce((sum, a) => sum + (parseFloat(a.discountedAmount.amount) || 0), 0)
  );

  const applicable = priced.discountCodes.some(
    (c) => c.code.toLowerCase() === code.toLowerCase() && c.applicable
  );
  if (!applicable || discount <= 0) {
    if (details && details.status !== "ACTIVE") {
      return { ok: false, reason: details.status === "EXPIRED" ? "โค้ดนี้หมดอายุแล้ว" : "โค้ดนี้ยังไม่เปิดใช้งาน" };
    }
    if (details === null) return { ok: false, reason: "ไม่พบโค้ดนี้ในระบบ" };
    return { ok: false, reason: "โค้ดนี้ใช้กับสินค้าในตะกร้าไม่ได้ หรือยอดยังไม่ถึงขั้นต่ำ" };
  }

  return { ok: true, code, title: (details?.title ?? code).replace(/^web:\s*/i, ""), discount };
}
